"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient()

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
        <GoogleOAuthProvider clientId="717564244556-16h3r2htoq67qsv3e385u3s1jp5eltn8.apps.googleusercontent.com">
          {children}
          <ReactQueryDevtools />
        </GoogleOAuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
